FROM ruby:2.6.3-slim-buster

# RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list
# RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN apt update && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_11.x | bash -

RUN apt install -y libpq-dev nodejs postgresql-client-11 locales locales-all \
    libcurl4-openssl-dev python3-dev python3-pip ruby ruby-dev git yarn imagemagick

RUN pip3 install awscli requests

RUN npm install elasticdump -g && \
    ACCEPT_HIGHCHARTS_LICENSE=YES npm install highcharts-export-server -g --unsafe-perm

RUN locale-gen en_US.UTF-8
RUN update-locale en_US.UTF-8

RUN gem update --system && gem install bundler

# Install sonarqube
ENV SONAR_SCANNER_VER 3.3.0.1492-linux
COPY sonar-waittask /usr/local/bin/
RUN curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VER}.zip && \
    unzip sonar-scanner-cli-${SONAR_SCANNER_VER}.zip && \
    mv sonar-scanner-${SONAR_SCANNER_VER}/ /opt/sonar-scanner-${SONAR_SCANNER_VER}/ && \
    rm sonar-scanner-cli-${SONAR_SCANNER_VER}.zip && \
    ln -s /opt/sonar-scanner-${SONAR_SCANNER_VER}/bin/sonar-scanner /usr/local/bin/sonar-scanner

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
