FROM ruby:2.6.3-alpine3.9

RUN apk --no-cache upgrade && \
    apk --no-cache add build-base git yarn ruby ruby-dev \
    nodejs nodejs-npm curl libcurl curl-dev postgresql-dev

RUN gem update --system && gem install bundler -v=1.17.3

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
