---
version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: apk add --no-cache make
      - run: make image

workflows:
  build_test_deploy:
    jobs:
      - build
